src/dev_ng/rage/framework/tools/src/web/ToolsPortal/ViewModels/UlogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;
using System.Xml.Linq;

using RSG.Pipeline.Core;
using RSG.Pipeline.Automation.Consumers;
using RSG.Pipeline.Automation.Common.Jobs;
using RSG.Pipeline.Automation.Common.Tasks;

using RSG.ToolsPortal.Classes;

namespace RSG.ToolsPortal.ViewModels
{
    /// <summary>
    /// 
    /// </summary>
    public class UlogViewModel : BaseViewModel
    {
        #region Properties
        /// <summary>
        /// Override The IconPath
        /// </summary>
        public override String IconPath
        {
            get
            {
                return ConfigurationManager.AppSettings["AppLogIconPath"];
            }
        }

        /// <summary>
        /// </summary>
        public String ServerHost { get; private set; }

        /// <summary>
        /// Property for storing the Job object
        /// </summary>
        public Job Job { get; private set; }

        /// <summary>
        /// Property for storing the ErrorsOnly flag as bool
        /// </summary>
        public bool ErrorsOnly { get; private set; }

        /// <summary>
        /// Property for storing the Ulog Content as an XML Doc
        /// </summary>
        public XDocument UlogXDocument { get; private set; }

        /// <summary>
        /// Property for storing the flag to render the download build monitor file button 
        /// </summary>
        public bool HasBuildMonitorFile { get; private set; }
        #endregion // Properties

        #region Constructor(s)
        /// <summary>
        /// Constructor
        /// </summary>
        public UlogViewModel() : base() { }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <param name="ulogXDocument"></param>
        public UlogViewModel(String serverHost, Job job, Boolean errorsOnly, XDocument ulogXDocument, bool hasBuildMonitorFile)
            : base()
        {
            this.ServerHost = serverHost;
            this.Job = job;
            this.ErrorsOnly = errorsOnly;
            this.UlogXDocument = ulogXDocument;
            this.HasBuildMonitorFile = hasBuildMonitorFile;
        }
        #endregion // Constructor(s)
    }

} // RSG.ToolsPortal.ViewModels namespace

src/dev_ng/rage/framework/tools/src/web/ToolsPortal/Controllers/UlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.IO;
using System.Text;
using System.Configuration;

using RSG.Pipeline.Automation.Common.Jobs;

using RSG.ToolsPortal.Classes;
using RSG.ToolsPortal.ViewModels;

namespace RSG.ToolsPortal.Controllers
{
    public class UlogController : ApplicationController
    {
        #region Methods / Controllers
        /// <summary>
        /// GET: /Ulog/ 
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <returns></returns>
        public ActionResult Index(String serverHost, String jobId, bool errorsOnly = false)
        {
            if ((serverHost == null) || (jobId == null)) {
                ModelState.AddModelError("", "Both ServerHost & JobId parameters must be provided");
                return View(new UlogViewModel());
            }

            UlogClass ulogWeb = new UlogClass(serverHost);
            Job job = ulogWeb.GetJob(jobId);
            XDocument ulogXMLDoc = ulogWeb.GetUlogXDocument(job);

            bool hasBuildMonitorFile = false;
            String buildMonitorFilename = ulogWeb.CheckFileAvailability(job, ConfigurationManager.AppSettings["BuildMonitorFilename"]);
            if (buildMonitorFilename != null)
            {
                hasBuildMonitorFile = true;
            }
            
            if (ModelState.IsValid && (ulogWeb.Exceptions.Count > 0))
            {
                foreach (KeyValuePair<String, Exception> ex in ulogWeb.Exceptions)
                {
                    ModelState.AddModelError("", ex.Key + ex.Value);
                }
            }

            return View(new UlogViewModel(serverHost, job, errorsOnly, ulogXMLDoc, hasBuildMonitorFile));
        }

        /// <summary>
        /// GET: /Ulog/Errors
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <returns></returns>
        public ActionResult Errors(String serverHost, String jobId)
        {
            UlogClass ulogWeb = new UlogClass(serverHost);
            Job job = ulogWeb.GetJob(jobId);
            List<String> errors = ulogWeb.GetErrors(job);

            return Json(errors, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetULog(String serverHost, String jobId)
        {
            UlogClass ulogWeb = new UlogClass(serverHost);
            Job job = ulogWeb.GetJob(jobId);

            String ulogContent = ulogWeb.GetUlogContent(job);

            return File(new MemoryStream(Encoding.UTF8.GetBytes(ulogContent ?? "")),
                        ConfigurationManager.AppSettings["UniversalLogFileMimeType"],
                        jobId + "-" + ConfigurationManager.AppSettings["UniversalLogFileName"]
                        );
        }

        /// <summary>
        /// Post: /Ulog/DownloadULog
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DownloadULog(String serverHost, String jobId)
        {
            UlogClass ulogWeb = new UlogClass(serverHost);
            Job job = ulogWeb.GetJob(jobId);

            String ulogContent = ulogWeb.GetUlogContent(job);

            return File(new MemoryStream(Encoding.UTF8.GetBytes(ulogContent ?? "")),
                        ConfigurationManager.AppSettings["UniversalLogFileMimeType"],
                        jobId + "-" + ConfigurationManager.AppSettings["UniversalLogFileName"]
                        );
        }

        /// <summary>
        /// Post: /Ulog/DownloadBuildMonitor
        /// </summary>
        /// <param name="serverHost"></param>
        /// <param name="jobId"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DownloadBuildMonitor(String serverHost, String jobId)
        {
            String localBuildMonitorFilepath = null;

            UlogClass ulogWeb = new UlogClass(serverHost);
            Job job = ulogWeb.GetJob(jobId);

            String buildMonitorFilename = ConfigurationManager.AppSettings["BuildMonitorFilename"];
            String remoteBuildMonitorFilename = ulogWeb.CheckFileAvailability(job, buildMonitorFilename);
            if (remoteBuildMonitorFilename != null)
            {
                localBuildMonitorFilepath = ulogWeb.DownloadJobFile(job, remoteBuildMonitorFilename);
            }

            MemoryStream stream = new MemoryStream(System.IO.File.ReadAllBytes(localBuildMonitorFilepath));
            ulogWeb.DeleteLocalFileIfExists(localBuildMonitorFilepath);

            return File(stream, ConfigurationManager.AppSettings["BuildMonitorMimeType"],
                        jobId + "-" +  buildMonitorFilename
                        );
        }
        #endregion //Methods / Controllers
    }

} //ToolsPortal.Controllers namespace

src/dev_ng/rage/framework/tools/src/web/ToolsPortal/Views/Ulog/Index.cshtml
@using System.Xml.Linq;
@model RSG.ToolsPortal.ViewModels.UlogViewModel

@{
    var pageTitle = "Universal Log Viewer";

    ViewBag.Title = pageTitle + Model.TitleSeparator + Model.Title;
    ViewBag.ContentTitle = Model.Title + Model.TitleSeparator + "<span class='last'>" + pageTitle;
    ViewBag.ContentDescription = " ServerHost: " + Model.ServerHost + " - " 
                                + "Job ID: " + ((Model.Job != null) ? Model.Job.ID.ToString() : "");

    var tableCloneId = "ulog-clone";                                
    var tableId = "ulog";
}

<!-- Import Ulog Style -->
@Styles.Render("~/Content/style/ulog")
<!-- Import Scripts -->
@Scripts.Render("~/bundles/ulog")

@Helpers.RenderJobInfoTable(@Model.Job)
@if ((Model.UlogXDocument != null) && (Model.UlogXDocument.Elements().Count() > 0)) {
    String NonErrorClass = String.Empty;
    if (!Model.ErrorsOnly) 
    {
        NonErrorClass = "selected";
    }
        
    <div id="filters">
        <span class="filter-wrap hand selected exception" key="exception" title="Toggle Exceptions">Exceptions</span>
        <span class="filter-wrap hand selected error tool_error" key="error" title="Toggle Errors">Errors</span>
        <span class="filter-wrap hand @NonErrorClass warning" key="warning" title="Toggle Warnings">Warnings</span>
        <span class="filter-wrap hand @NonErrorClass message" key="message" title="Toggle Info Messages">Info Messages</span>
        <span class="filter-wrap hand @NonErrorClass profile" key="profile" title="Toggle Profile Messages">Profile Messages</span>
        <span class="filter-wrap hand @NonErrorClass debug" key="debug" title="Toggle Debug Messages">Debug Messages</span>
        <input type="text" id="filter" title="Type text to filter" />
    </div>
    
    <table class="title-only">
        <thead>
            <tr>
                <th class="title">
                    <span id="job-type">@Model.Job.GetType().ToString().Split('.').Last() (Hover for More Info)</span>
                    <span id="colvis-button"></span>
                    
                    <span style="float: right;">
                        @using (Html.BeginForm("DownloadULog", "Ulog", FormMethod.Post, new { id = "download-ulog-form" })) {
                            @Html.AntiForgeryToken()
                            <input type="hidden" id="ServerHost" name="ServerHost" value="@Model.ServerHost">
                            <input type="hidden" id="JobID" name="JobID" value="@Model.Job.ID">

                            <input id="download-ulog-button" class="red-button hand" type="submit" 
                                       name="download-ulog-button" title="Download Log" value="Download Log" />
                        }
                    </span>
                    @if (@Model.HasBuildMonitorFile) {
                        <span style="float: right;">
                            @using (Html.BeginForm("DownloadBuildMonitor", "Ulog", FormMethod.Post, new { id = "download-buildmon-form" }))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" id="ServerHost" name="ServerHost" value="@Model.ServerHost">
                                <input type="hidden" id="JobID" name="JobID" value="@Model.Job.ID">

                                <input id="download-buildmon-button" class="red-button hand" type="submit" 
                                           name="download-buildmon-button" title="Download Build Monitor" value="Download Build Monitor" />
                            }
                        </span>
                    }
                </th>
            </tr>
        </thead>
    </table>
    
    <table id="@tableCloneId" class="tablesorter hidden">
        <thead>
            <tr>
                <th class="level-cell" title="Level">Level</th>
                <th class="timestamp-cell" title="Timestamp">Timestamp</th>
                <th class="context-cell" title="System Context">System Context</th>
                <th class="context-cell" title="Message Context">Message Context</th>
                <th class="message-cell" title="Message">Message</th>
            </tr>
        </thead>

    @foreach (var systemContext in Model.UlogXDocument.Descendants("context"))
    {
        foreach (var element in systemContext.Elements())
        {
            XAttribute timeticks = element.Attribute("timestamp_ticks");
            if (timeticks != null) 
            {

                DateTime timestamp = new DateTime(Convert.ToInt64(@timeticks.Value), DateTimeKind.Utc);
                String SystemContext = (@systemContext.Attribute("name") != null) ? @systemContext.Attribute("name").Value : String.Empty;
                String MessageContext = (@element.Attribute("context") != null) ? @element.Attribute("context").Value : String.Empty;
                String Value = (@element.Value != null) ? @element.Value : String.Empty;
                String Name = (@element.Name != null) ? @element.Name.ToString() : String.Empty;
            
                <tr class="@Name" key="@Name">
                    <td class="cell-icon" title="@Name"></td>
                    <td class="timestamp-cell" title="@timestamp.ToString("s")">@timestamp.ToString("s")</td>
                    <td class="context-cell" title="@SystemContext">@Helpers.TruncateString(@SystemContext, 35)</td>
                    <td class="context-cell" title="@MessageContext">@Helpers.TruncateString(@MessageContext, 35)</td>
                    <td class="message-cell" title="@element.Value">@element.Value</td>
                </tr>
            }
        }
    }
    </table>
    
    <table id="@tableId">
        <thead>
            <tr>
                <th class="level-cell" title="Level">Level</th>
                <th class="timestamp-cell" title="Timestamp">Timestamp</th>
                <th class="context-cell" title="System Context">System Context</th>
                <th class="context-cell" title="Message Context">Message Context</th>
                <th class="message-cell" title="Message">Message</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    
    <script type="text/javascript">
        $(document).ready(function() {
            setupUlog("@tableCloneId", "@tableId");
        });
    </script>    
}

